# Generated by Django 2.0.1 on 2018-08-08 02:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='city')),
                ('desc', models.CharField(max_length=200, verbose_name='desc')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='course_org')),
                ('desc', models.TextField(verbose_name='org_desc')),
                ('click_num', models.IntegerField(default=0, verbose_name='click_num')),
                ('fav_num', models.IntegerField(default=0, verbose_name='fav_num')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='cover')),
                ('address', models.CharField(max_length=150, verbose_name='org_addr')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='the_city')),
            ],
            options={
                'verbose_name': 'org',
                'verbose_name_plural': 'org',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='teacher_name')),
                ('work_years', models.IntegerField(default=0, verbose_name='teacher_year')),
                ('work_company', models.CharField(max_length=50, verbose_name='work_company')),
                ('work_position', models.CharField(max_length=50, verbose_name='work_position')),
                ('points', models.CharField(max_length=50, verbose_name='points')),
                ('click_num', models.IntegerField(default=0, verbose_name='click_num')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='fav_num')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='org')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teacher',
            },
        ),
    ]
