# Generated by Django 2.0.1 on 2018-08-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180811_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='iamge',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
