# Generated by Django 2.0.1 on 2018-08-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='iamge',
            new_name='image',
        ),
    ]
