# Generated by Django 2.0.1 on 2018-08-09 22:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180808_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'verbose_name': '留言板', 'verbose_name_plural': '留言板'},
        ),
        migrations.AlterModelOptions(
            name='userask',
            options={'verbose_name': '用户咨询', 'verbose_name_plural': '用户咨询'},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '用户课程表', 'verbose_name_plural': '用户课程表'},
        ),
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '用户消息', 'verbose_name_plural': '用户消息'},
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='comments',
            field=models.CharField(max_length=250, verbose_name='留言'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='course_name',
            field=models.CharField(max_length=50, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='name',
            field=models.CharField(max_length=20, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, 'course'), (2, 'org'), (3, 'teacher')], default=1, verbose_name='收藏类型'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='has_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=500, verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.IntegerField(default=0, verbose_name='接收用户'),
        ),
    ]
