# Generated by Django 2.1 on 2018-08-07 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='class_name')),
                ('desc', models.CharField(max_length=300, verbose_name='class_desc')),
                ('detail', models.TextField(verbose_name='class_detail')),
                ('degree', models.CharField(choices=[('cj', 'primary'), ('zj', 'middle'), ('gj', 'high')], max_length=2)),
                ('learn_times', models.IntegerField(default=0, verbose_name='learn_time(min)')),
                ('students', models.IntegerField(default=0, verbose_name='learn_num')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='fav_num')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='cover')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click_num')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='create_time')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'class',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='resource_name')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='resource_file')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course_resource',
                'verbose_name_plural': 'course_resource',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='lesson_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='video_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='lesson')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
            },
        ),
    ]
