# Generated by Django 2.0.1 on 2018-08-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180816_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='moble',
            new_name='mobile',
        ),
    ]
